### ISSUE TITLE
Bizarre spelling

### ISSUE THREAD

**Issue by M0nsteR** [mp-hl-2021/splinter#2]
I find it rather bizarre to raise a special issue to simply fix the spelling of "bizarre".. but I couldn't help doing it.

**Comment by M0nsteR** [comment]
Hi folks, any progress on this issue? This glaring typo makes my eyes bleed every time I read your README. :cow2:

**Comment by shananton** [comment]
Thanks for your feedback! We are working to resolve the issue as quickly as we can!

Here's a sneak peek at the current state of the fix:
![image](https://user-images.githubusercontent.com/21276207/113515352-b334d700-957c-11eb-9473-aaafc7e82e16.png)

**Comment by M0nsteR** [comment]
Guys, you're epic! 🚀

**Comment by vsalavatov** [comment]
:tada: :tada: :tada:

**Comment by M0nsteR** [comment]
Hey guys.. I wish I had the same amount of excitement about this bug fix, however I can still see this very same nasty typo in the About description of your wonderful project. =(

**Comment by tsarn** [comment]
Fixed
